services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx
    depends_on:
     - front
     - back
    ports:
     - "4430:443"
    networks:
     - transcendence
    volumes:
     - front:/var/www/html
     - images:/var/www/html/src/img/userPfp
    restart: on-failure

  front:
    build:
      context: ./front/
      dockerfile: ../docker/front/Dockerfile
    container_name: front
    depends_on:
     - back
    networks:
     - transcendence
    volumes:
      - front:/usr/src/app
      - ./front/src/ts:/usr/src/app/src/ts
    restart: on-failure
    command: npm run dev

  back:
    build: 
      context: ./back/server/.
      dockerfile: ../../docker/back/Dockerfile
    container_name: back 
    env_file: ../.env
    volumes:
      - db:/home/prisma
      - images:/home/front/src/img/userPfp
      - ./back/server/src:/home/src
      - ./back/server/pong:/home/pong
    networks:
      - transcendence
    restart: on-failure
    expose: 
      - "3000"
      - "3002"
    command: npm run dev

networks:
  transcendence:
    driver: bridge

volumes:
  db:
  front:
  images:
