services:
  nginx:
    build: docker/nginx/.
    env_file: ../.env
    container_name: nginx
    depends_on:
      - front
      - back
      - db
    ports:
      - "443:443"
        #    volumes:
        #      - front:/
    networks:
      - transcendence
    restart: on-failure

  front:
    build: docker/front/.
    env_file: ../.env
    container_name: front
    depends_on:
      - back
      - db
    volumes:
      - front:/home
    networks:
      - transcendence
    restart: on-failure
      #    expose:
      #      - ""

  back:
    build: docker/back/.
    env_file: ../.env
    container_name: back 
    depends_on:
      - db
    volumes:
      - back:/home
    networks:
      - transcendence
    restart: on-failure
      #    ports:
      #- "3000:3000"
    expose:
      - "3000"

  db:
    build: docker/db/.
    env_file: ../.env
    container_name: db
    volumes:
      - db:/home
    networks:
      - transcendence
    restart: on-failure
    expose:
      - "3306"
      #- "8191"


networks:
  transcendence:
    driver: bridge

volumes:
  back:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'back/'
  db:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: 'db/'
  front:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: 'front/'
