services:
  nginx:
    build: docker/nginx/.
    env_file: ../.env
    container_name: nginx
    depends_on:
     - front
     - back
    ports:
     - "4430:443"
    networks:
     - transcendence
    volumes:
     - nginx:/var/www/html
    restart: on-failure

  front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    env_file: ../.env
    container_name: front
    depends_on:
     - back
    ports: 
     - "8080:3001"
    volumes:
     - front:/usr/src/app
    networks:
     - transcendence
    restart: on-failure

  back:
    build: 
      context: ./back/server/.
      dockerfile: ../../docker/back/Dockerfile
    env_file: ../.env
    container_name: back 
    volumes:
      - db:/home/prisma
      - ./back/server/src:/home/src #remove when in production
      - ./back/server/pong/js:/home/pong/js #remove when in production
      - ./front/src/img:/home/front/src/img #used for profile pic upload by user
    networks:
      - transcendence
    restart: on-failure
    ports:
      - "3000:3000" #ne pas oublier d'enlever au moment de rendre le projet
    expose: 
      - "3002"
    command: npm run dev #remove when in production

networks:
  transcendence:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'back/volume'

  front:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'front'
  
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'front'
