server {
	listen 443 ssl;
	listen [::]:443 ssl;

	server_name zigotos.42.fr www.zigotos.42.fr;

	ssl_certificate /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;
	ssl_protocols TLSv1.3;
	
	root /var/www/html;
	index src/index.html index.html;
	
	location / {
		autoindex on;
		autoindex_format html;
	}
	
	location /css/ {
		alias /var/www/html/src/css/;
	}
	
	location /js/ {
		alias /var/www/html/src/js/;
	}

	location /views/ {
		alias /var/www/html/src/views/;
	}

	location /fonts/ {
		alias /var/www/html/src/fonts/;
	}

	location /img/ {
		alias /var/www/html/src/img/;
	}

	location /game/ {
		alias /var/www/html/src/game/; 
	}

	location /login {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /logout {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /register {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /profile/grab {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}

	location /profile/edit {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /profile/password {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend/requested {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend/request {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend/accept {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend/reject {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /friend/delete {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /file_upload {
    proxy_pass http://back:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
	}
}
