server {
	listen 8443 ssl;
	listen [::]:8443 ssl;

	server_name $nginx_domain www.$nginx_domain;

	ssl_certificate /etc/ssl/certs/inception.crt;
	ssl_certificate_key /etc/ssl/private/inception.key;

	ssl_protocols TLSv1.3;
	
	root /var/www/html;
	index index.html;
	
	location / {
		autoindex on;
		autoindex_format html;
		try_files $uri $uri/ =404;
	}
}
